BOOKMOTION/BOOKMOTION/urls.py
from django.contrib import admin
from django.urls import include,path

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ELIB.urls', namespace='ELIB')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BOOKMOTION/ELIB/urls.py
from django.urls import path
from ELIB import views

app_name = 'ELIB'

urlpatterns = [
    path('', views.home, name='home-page'),
    path('details/<str:slug>/', views.details, name='details'),
    path('borrow/<str:slug>/', views.borrow, name='borrow'),
    path('borrowed/', views.borrowed, name='borrowed'),
    path('upload/', views.upload, name='upload'),
]

BOOKMOTION/ELIB/models.py
from django.db import models
from django.utils import timezone
from auth_app.models import Student
from django.utils.translation import gettext_lazy as _

from django.utils.text import slugify
import os
import uuid
from django.contrib.auth.models import User
from django.db.models.signals import post_delete
from django.dispatch import receiver


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s-%s.%s" % (instance.slug, uuid.uuid4(), ext)
    return os.path.join('books/', filename)


class Genre(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    name = models.CharField(verbose_name="Author's Name", max_length=100)
    added_on = models.DateField(verbose_name="Added On", default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-added_on']


class Book(models.Model):
    title = models.CharField("Title", max_length=150)
    description = models.TextField("Description")
    author = models.ForeignKey(to=Author, on_delete=models.CASCADE)
    genres = models.ManyToManyField(Genre)
    is_available = models.BooleanField(verbose_name="Is Available", default=True)
    cover = models.ImageField(
        verbose_name=_('Cover'),
        upload_to=get_file_path,
        default='./books/ELIB_book.wep3'
    )
    slug = models.SlugField(
        _("Safe Url"),
        unique=True,
        blank=True,
        null=True,
    )
    added_on = models.DateField(verbose_name="Added On", default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title[:50])

        self.title = self.title.title()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-added_on']


class BorrowedBook(models.Model):
    User = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='user')
    book = models.OneToOneField(Book, on_delete=models.CASCADE, related_name='book')
    return_date = models.DateField('Return Date', blank=True, null=True)
    borrowed = models.DateField(verbose_name="Borrowed On", default=timezone.now)
    fine = models.IntegerField('Fine', default=0)

    def __str__(self):
        return "{} - {}".format(self.book.title, self.user.username)


@receiver(post_delete, sender=BorrowedBook)
def signal_function_name(sender, instance, using, **kwargs):
    book = instance.book
    book.is_available = True
    book.save()

BOOKMOTION/ELIB/forms.py
from django.forms import ModelForm
from django import forms

from .models import Book, Genre


class BookFormManager(ModelForm):
    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'genre'}),
    )

class Meta:
    fields = ('title', 'description', 'author', 'cover')
    model = Book

def __init__(self, *args, **kwargs):
    super(BookFormManager, self).__init__(*args, **kwargs)

    for visible in self.visible_fields():
        visible.field.widget.attrs['class'] = 'form-control form-control-lg'

BOOKMOTION/ELIB/views.py
from dataclasses import dataclass
from django.shortcuts import render, redirect
from django.urls import reverse
from ELIB import models

from ELIB.forms import BookFormManager

import datetime


# Create your views here.

def home(request):
    if request.GET.get('search', []):
        books = models.Book.objects.filter(title__contains=request.GET.get('search')).order_by('-id')
    else:
        books = models.Book.objects.all().order_by('-id')
    context_data = {
        'books': books
    }
    return render(request, 'elib/cover.html', context=context_data)


def details(request, slug):
    book = models.Book.objects.filter(slug=slug)[0]

    genres = models.Genre.objects.filter(book=book)

    context_data = {
        'book': book,
        'genres': genres
    }
    return render(request, 'elib/details.html', context=context_data)


def borrow(request, slug):
    if not request.user.is_authenticated:
        return redirect(reverse('auth_app:home'))

    # fetch book
    book = models.Book.objects.filter(slug=slug).first()
    if book.is_available:
        # do the borrowing
        # create an instance in the borrowed book table
        borrowed_book = models.BorrowedBook(user=request.user, book=book)

        # get return data after 30 days
        today = datetime.date.today()
        return_date = today + datetime.timedelta(days=30)
        borrowed_book.return_date = return_date

        # make book unavailable
        book.is_available = False
        book.save()

        # save borrowed book
        borrowed_book.save()

        return redirect(reverse('elib:borrowed'))


def borrowed(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            records = models.BorrowedBook.objects.all().order_by('-borrowed')
        else:
            records = models.BorrowedBook.objects.filter(user=request.user).order_by('-borrowed')
        context_data = {
            'records': records
        }
        return render(request, 'elib/borrowed.html', context=context_data)

    return redirect(reverse('auth_app:home'))


def upload(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            if request.method == "POST":
                form = BookFormManager(request.POST, request.FILES)
                if form.is_valid():
                    form.save()
                    return redirect(reverse('ELIB:home-page'))
                return render(request, 'ELIB/upload.html', context={'form': form, 'error_msg': "Please valid data."})
            return render(request, 'ELIB/upload.html', context={'form': BookFormManager()})

        return redirect(reverse('ELIB:home-page'))

    return redirect(reverse('auth_app:home'))


def login(request):
    return render(request, 'login.html')


def librarian(request):
    return render(request, 'Librarian signup.html')


def student(request):
    return render(request, 'student signup.html')

templates/ELIB/Upload.html
{% extends '../layout.html' %}
{% load static %}

{% block content %}

<style>
  .form-area {
    margin: 5% auto;
    width: 80vw;
    border: 1px solid lightgray;
    padding: 2rem 3rem;
  }
  form input[type='checkbox'] {
    width: 1rem;
    aspect-ratio: 1;
  }
  form p {
    overflow: hidden;
  }
  form #id_genres {
    display: flex;
    gap: 1rem;
  }
  form #id_genres div label{
    display: flex;
    align-items: center;
    gap: .5rem;
  }
</style>

<div class="form-area">

  {% if error_msg %}
    <div class="alert alert-danger"  role="alert">
      {{ error_msg }}
    </div>
  {% endif%}

  <form action="{% url 'elib:upload' %}" method="post" enctype="multipart/form-data">

    {{ form.as_p }}

    {% csrf_token %}

    <div class="pt-1 mb-4">
      <input class="btn btn-dark btn-lg btn-block" type="submit" value="Upload Book">
    </div>
  </form>

</div>



{% endblock content %}

templates/ELIB/borrowed.html
{% extends '../layout.html' %}
{% load static %}

{% block content %}

  <style>

    .borrowed .card {
      padding: .5rem 1rem;
      display: grid;
      gap: .5rem;
      justify-content: center;
    }
    .card p {
      margin: .25rem;
    }
    img {
      height: 60vh;
    }

  </style>

  <div class="grid-container borrowed">
      {% for record in records %}
        <div class="grid-item">
          <a href="{% url 'elib:details' record.book.slug %}">
            <img src="/media/{{record.book.cover}}" alt="">
          </a>
          <div class="card">
              <span class="card-content">
                {% if request.user.is_staff %}
                  <p>
                    <span>Student: </span>
                    <span>{{ record.user|title }}</span>
                  </p>
                {% endif %}
                <p>
                  <span>Return date: </span>
                  <span>{{ record.return_date }}</span>
                </p>
              </span>
          </div>
        </div>
      {% endfor %}

  </div>

  {% if not records %}
    <div class="alert alert-primary" style="width: max-content; margin: 3rem auto;" role="alert">
      No Books Found!
    </div>
  {% endif%}

{% endblock content %}

templates/ELIB/cover.html
{% extends '../layout.html' %}
{% load static %}

{% block content %}
  <div class="grid-container">
      {% for book in books %}
        <div class="grid-item">
          <a href="{% url 'elib:details' book.slug %}">
            <img src="/media/{{book.cover}}" alt="">
          </a>
        </div>
      {% endfor %}

  </div>

  {% if not books %}
    <div class="alert alert-primary" style="width: max-content; margin: 3rem auto;" role="alert">
      No Books Found!
    </div>
  {% endif%}

{% endblock content %}

templates/ELIB/details.html
{% extends '../layout.html' %}
{% load static %}

{% block content %}

<style>
  img{
    height: 500px;
    width: 500px;
    margin: 10px 400px;
    border-radius: 5px;
  }
  h3{
    text-align: center;
  }
  button{
    margin: 10px;
  }
  body{
    color: white;
    background-color: #9A616D;
  }
  .img-wrapper {
    position: relative;
    overflow: hidden;
    isolation: isolate;
    padding: 0;
  }
  .img-wrapper img {
    width: 100%;
    height: 100%;
    margin: 0;
  }
  .img-wrapper span {
    position: absolute;
    top: 1rem;
    right: 1rem;
    padding: 1rem 2rem;
    background-color: red;
  }
  .img-wrapper span.available {
    background-color:  blue;
  }
</style>

  <div style="display: grid; grid-template-columns: 1fr 2fr; justify-items: center; gap: 3rem; padding: 2rem 5rem">
    <div class="img-wrapper">
      <img src="/media/{{book.cover}}" alt="">
      {% if book.is_available %}
        <span class="available">Available</span>
      {% else %}
        <span>Not Available</span>
      {% endif %}
    </div>
    <div>
      <h3>{{book.title}}</h3>
      <p>
        <span>Author: </span>
        <span>{{book.author}}</span>
      </p>
      <p>
        <span>Genre: </span>
        {% for genre in genres %}
          <span>{{genre}}</span>
        {% endfor %}
      </p>
      <P>
        {{book.description}}
      </P>
      {% if book.is_available %}
        <a href="{% url 'elib:borrow' book.slug %}" class="btn btn-primary btn-lg btn-block">BORROW</a>
      {% endif %}
    </div>
  </div>


{% endblock content %}

templates/ELIB/navbar.html
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">ELIB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto p-3">
        <li class="nav-item active">
          <a class="nav-link" href="#">HOME <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">ABOUT</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            BROWSE
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Romance</a>
            <a class="dropdown-item" href="#">Fantasy</a>
            <a class="dropdown-item" href="#">History</a>
            <a class="dropdown-item" href="#">Crime</a>
            <a class="dropdown-item" href="#">Educative</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="./index.html">LOG IN</a>
        </li>
      </ul>