BOOKMOTION/BOOKMOTION/urls.py
from django.contrib import admin
from django.urls import include,path

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ELIB.urls', namespace='ELIB')),
    path('auth/', include('auth_app.urls', namespace='auth_app')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BOOKMOTION/ELIB/urls.py
from django.urls import path
from ELIB import views

app_name = 'ELIB'

urlpatterns = [
    path('', views.home, name='home-page'),
    path('details/<str:slug>/', views.details, name='details'),
    path('borrow/<str:slug>/', views.borrow, name='borrow'),
    path('borrowed/', views.borrowed, name='borrowed'),
    path('upload/', views.upload, name='upload'),
]

BOOKMOTION/auth_app/urls.py
from django.urls import path
# noinspection PyUnresolvedReferences
from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('', views.home, name='home'),
    # student
    path('register-student/', views.register, name='register-student'),
    path('login-student/', views.login_student, name='login-student'),
    path('logout/', views.logout_user, name='logout'),

    # staff
    path('login-staff/', views.login_staff, name='login-staff'),
    ]

BOOKMOTION/auth_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Student(AbstractUser):
    reg_no = models.CharField('Identity Card Number', unique=True, max_length=30, blank=True, null=True)

    # USERNAME_FIELD = 'reg_no'

    def __str__(self) -> str:
        if not self.get_full_name():
            return self.get_username()
        return self.get_full_name()

BOOKMOTION/auth_app/forms.py
from django.forms import ModelForm
from django import forms

from auth_app.models import Student

class UserForm(ModelForm):
    class Meta:
        fields=('username', 'reg_no', 'email', 'password')
        model = Student
        widgets = {
            "password": forms.PasswordInput(attrs={'autocomplete': '0ff', 'data-toggle': 'password'}),
        }

    def __int__(self,*args, **kwargs):
        super(UserForm, self).__int__(*args, **kwargs)

        for fieldname in ['username']:
            self.fields[fieldname].help_text = None

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'

BOOKMOTION/auth_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from auth_app.models import Student
from auth_app.forms import UserForm
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def home(request):
    return render(request, 'auth_app/index.html')


def login_student(request):
    if request.user.is_authenticated:
        return redirect(reverse('ELIB:home-page'))
    if request.method == "POST":
        reg_no = request.POST.get('reg_no')
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('ELIB:home-page'))

        return render(request, 'auth_app/login-student.html',
                      context={'error_msg': "Credentials not valid! Please try again."})
    return render(request, 'auth_app/login-student.html')


def register(request):
    if request.user.is_authenticated:
        return redirect(reverse('ELIB:home-page'))
    if request.method == "POST":
        if Student.objects.filter(username=request.POST.get('username')):
            form = UserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect(reverse('auth_app:login-student'))
            return render(request, 'auth_app/register-student.html', context={'error_msg': "Data entered not valid"})
        return render(request, 'auth_app/register-student.html', context={'error_msg': "Username Already Exists."})

    return render(request, 'auth_app/register-student.html', context={'form': UserForm()})


def login_staff(request):
    if request.user.is_authenticated:
        return redirect(reverse('ELIB:home-page'))
    if request.method == "POST":
        reg_no = request.POST.get('reg_no')
        username = request.POST.get('username')
        password = request.POST.get('password')

        # check if user is staff
        _user = Student.objects.filter(username=username).first()
        print("+" * 10)
        print(_user.is_staff)
        if _user.is_staff:
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect(reverse('ELIB:home-page'))

            return render(request, 'auth_app/login-staff.html',
                          context={'error_msg': "Credentials not valid! Please try again."})

        return render(request, 'auth_app/login-staff.html', context={'error_msg': "Staff Acount not found."})
    return render(request, 'auth_app/login-staff.html')


def logout_user(request):
    logout(request)
    return redirect(reverse("auth_app:home"))

templates/auth_app/index.html
{% extends '../layout.html' %}
{% load static %}


{% block content %}
  <div>
    <section class="vh-100" style="background-color: #9A616D;">
      <div class="container py-9 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-9 col-lg-5 d-none d-md-block">
                  <img style="width: 100%; height: 100%;" src="{% static 'images/elib_book.webp' %}"
                    alt="login form" class="img-fluid" style="border-radius: 1rem ;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">
                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-2 ml-8 ">ELIB</span>
                      </div>
                      <div class="pt-1 mb-4">
                        <a href="{% url 'auth_app:login-student' %}" class="btn btn-dark btn-lg btn-block">Sign In As Student</a>
                      </div>

                      <div class="pt-1 mb-4">
                        <a href="{% url 'auth_app:login-staff' %}" class="btn btn-dark btn-lg btn-block">Sign In As Staff</a>
                      </div>

                      <a class="small text-muted" href="#!">Forgot password?</a>
                      <p class="mb-5 pb-lg-2 text-muted">Don't have an account? <a href="{% url 'auth_app:register-student' %}"
                        style="color: #393f81;">Create New Account</a></p>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
{% endblock content %}

templates/auth_app/login-staff.html
{% extends '../layout.html' %}
{% load static %}


{% block content %}
  <div>
    <section style="background-color: #9A616D;padding: 2rem 0;">
      <div class="container py-9 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-9 col-lg-5 d-none d-md-block">
                  <img style="width: 100%; height: 100%;" src="{% static 'images/elib_book.webp' %}"
                    alt="login form" class="img-fluid" style="border-radius: 1rem ;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">
                    <form method="POST" action="{% url 'auth_app:login-staff' %}">
    
                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-2 ml-8 ">ELIB</span>
                      </div>
    
                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>
                      

                      

                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example17">Username</label>
                        <input type="text" id="form2Example17" name="username" class="form-control form-control-lg" required />
                      </div>
    
                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example17">Identity Card Number</label>
                        <input type="text" id="form2Example17" name="reg_no" class="form-control form-control-lg" />
                      </div>
    
                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example27">Password</label>
                        <input type="password" name="password" id="form2Example27" class="form-control form-control-lg" />
                      </div>
    
                      <div class="pt-1 mb-4">
                        <input class="btn btn-dark btn-lg btn-block" type="submit" value="Login">
                      </div>
    
                      <a class="small text-muted" href="#!">Forgot password?</a>
                      <p class="mb-5 pb-lg-2 text-muted">Don't have an account? <a href="{% url 'auth_app:register-student' %}"
                        style="color: #393f81;">Create New Account</a></p>
    
                    </form>
    
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
{% endblock content %}

templates/auth_app/login-student.html
{% extends '../layout.html' %}
{% load static %}


{% block content %}
  <div>
    <section style="background-color: #9A616D;padding: 2rem 0;">
      <div class="container py-9 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-9 col-lg-5 d-none d-md-block">
                  <img style="width: 100%; height: 100%;" src="{% static 'images/elib_book.webp' %}"
                    alt="login form" class="img-fluid" style="border-radius: 1rem ;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">
                    <form method="POST" action="{% url 'auth_app:login-student' %}">

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-2 ml-8 ">ELIB</span>
                      </div>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>


                      {% if error_msg %}
                        <div class="alert alert-danger" role="alert">
                          {{error_msg}}
                        </div>
                      {% endif %}

                      {% csrf_token %}

                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example17">Username</label>
                        <input type="text" id="form2Example17" name="username" class="form-control form-control-lg" required />
                      </div>

                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example17">Identity Card Number</label>
                        <input type="text" id="form2Example17" name="reg_no" class="form-control form-control-lg" />
                      </div>

                      <div class="form-outline mb-4">
                        <label class="form-label" for="form2Example27">Password</label>
                        <input type="password" name="password" id="form2Example27" class="form-control form-control-lg" />
                      </div>

                      <div class="pt-1 mb-4">
                        <input class="btn btn-dark btn-lg btn-block" type="submit" value="Login">
                      </div>

                      <a class="small text-muted" href="#!">Forgot password?</a>
                      <p class="mb-5 pb-lg-2 text-muted">Don't have an account? <a href="{% url 'auth_app:register-student' %}"
                        style="color: #393f81;">Create New Account</a></p>

                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
{% endblock content %}

templates/auth_app/login.html
{% extends '../layout.html' %}
{% load static %}


{% block content %}
  <div>
    <section class="vh-100" style="background-color: #9A616D;">
      <div class="container py-9 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-9 col-lg-5 d-none d-md-block">
                  <img style="width: 100%; height: 100%;" src="{% static 'images/elib_book.webp' %}"
                    alt="login form" class="img-fluid" style="border-radius: 1rem ;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">
                    <form>

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-2 ml-8 ">ELIB</span>
                      </div>

                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                      <div class="form-outline mb-4">
                        <input type="email" id="form2Example17" class="form-control form-control-lg" />
                        <label class="form-label" for="form2Example17">Email address</label>
                      </div>

                      <div class="form-outline mb-4">
                        <input type="password" id="form2Example27" class="form-control form-control-lg" />
                        <label class="form-label" for="form2Example27">Password</label>
                      </div>

                      <div class="pt-1 mb-4">
                        <button class="btn btn-dark btn-lg btn-block" type="button">Login</button>
                      </div>

                      <a class="small text-muted" href="#!">Forgot password?</a>
                      <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="./landing.html"
                          style="color: #393f81;">Register here</a></p>
                      <a href="#!" class="small text-muted">Terms of use.</a>
                      <a href="#!" class="small text-muted">Privacy policy</a>
                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
{% endblock content %}

templates/auth_app/register-staff.html
{% extends '../layout.html' %}
{% load static %}


{% block content %}
  <div>
    <section style="background-color: #9A616D; padding: 2rem 0;">
      <div class="container py-9">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-9 col-lg-5 d-none d-md-block">
                  <img style="width: 100%; height: 100%;" src="{% static 'images/elib_book.webp' %}"
                    alt="login form" class="img-fluid" style="border-radius: 1rem ;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">
                    <form method="POST" action="{% url 'auth_app:register-student' %}">

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-2 ml-8 ">ELIB</span>
                      </div>
                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Create Account </h5>

                      {% if error_msg %}
                        <div class="alert alert-danger" role="alert">
                          {{error_msg}}
                        </div>
                      {% endif %}

                      {{ form.as_p }}

                      {% csrf_token %}

                      <div class="pt-1 mb-4">
                        <input class="btn btn-dark btn-lg btn-block" type="submit" value="Create Account">
                      </div>

                      <p class="mb-5 pb-lg-2" style="color: #393f81;"><a href="{% url 'auth_app:home' %}"
                          style="color: #393f81;">Already have an account?
                        </a>
                      </p>

                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
{% endblock content %}

templates/auth_app/register-student.html
{% extends '../layout.html' %}
{% load static %}


{% block content %}
  <div>
    <section style="background-color: #9A616D; padding: 2rem 0;">
      <div class="container py-9">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-9 col-lg-5 d-none d-md-block">
                  <img style="width: 100%; height: 100%;" src="{% static 'images/elib_book.webp' %}"
                    alt="login form" class="img-fluid" style="border-radius: 1rem ;" />
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black">
                    <form method="POST" action="{% url 'auth_app:register-student' %}">

                      <div class="d-flex align-items-center mb-3 pb-1">
                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                        <span class="h1 fw-bold mb-2 ml-8 ">ELIB</span>
                      </div>
                      <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Create Account </h5>

                      {% if error_msg %}
                        <div class="alert alert-danger" role="alert">
                          {{error_msg}}
                        </div>
                      {% endif %}

                      {{ form.as_p }}

                      {% csrf_token %}

                      <div class="pt-1 mb-4">
                        <input class="btn btn-dark btn-lg btn-block" type="submit" value="Create Account">
                      </div>

                      <p class="mb-5 pb-lg-2" style="color: #393f81;"><a href="{% url 'auth_app:home' %}"
                          style="color: #393f81;">Already have an account?
                        </a>
                      </p>

                    </form>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  </div>
{% endblock content %}